erp_lakehouse:
  target: dev
  outputs:
    dev:
      type: databricks
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH_DEV') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      schema: "{{ env_var('DBT_SCHEMA_DEV', 'hongwei') }}"
      catalog: "{{ env_var('DBT_CATALOG', 'erp_northwind') }}"
    prod:
      type: databricks
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH_PROD') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      schema: "{{ env_var('DBT_SCHEMA_PROD', 'prod') }}"
      catalog: "{{ env_var('DBT_CATALOG', 'erp_northwind') }}"
